##################
#  Input section  #
###################
[input]
### TLS, not using coroutines
type = "tcp"
format = "gelf"
listen = "0.0.0.0:22202"
framing = "nul"
tcp_threads = 2

####################
#  Output section  #
####################
[output]
### Debug output (stdout)
#type = "stdout"

### Kafka output
type = "kafka"
kafka_brokers = [ "kafka-1.alpha.thot.ovh.com:9094", "kafka-2.alpha.thot.ovh.com:9094" ]
kafka_topic = "alpha.log1"
kafka_threads = 1
kafka_coalesce = 10
kafka_timeout = 30000
kafka_acks = 0
kafka_compression = "gzip"
kafka_flush_interval = 6000

### Output format and parameters
### JSON (GELF)
format = "gelf"

[output.gelf_extra]
X-OVH-INPUT = "gelf-clear"