##################
#  Input section  #
###################
[input]
### TLS, not using coroutines
type = "tcp"
format = "gelf"
listen = "0.0.0.0:22202"
framing = "nul"
tcp_threads = 2

####################
#  Output section  #
####################
[output]
### Debug output (stdout)
#type = "stdout"

### Kafka output
type = "kafka"
topic = "myTopic"
threads = 5

### Output format and parameters
### JSON (GELF)
format = "gelf"
# gelf_default_message = "-"

[output.gelf_extra]
X-OVH-INPUT = "gelf-clear"

[output.librdkafka]
"bootstrap.servers" = "kafka.example.com:9094"
"message.timeout.ms" = "30000"
"request.required.acks" = "0"
"compression.codec" = "zstd"